language: python

notifications:
  email:
    on_success: never

cache:
  directories:
    - $HOME/.cache/pip

env:
  - IMGAUG_NO_CV2_INSTALLED_CHECK=TRUE

matrix:
  include:
#    - os: linux
#      python: 2.7
#    - os: linux
#      python: 3.5
#    - os: linux
#      python: 3.6
#    - os: linux
#      python: 3.7
#      dist: xenial
#      sudo: true
#    - os: windows
#      python: 2.7
#    - os: windows
#      python: 3.5
#    - os: windows
#      python: 3.6
#    - os: windows
#      python: 3.7
    - os: windows
      language: sh
      python: '3.6'
      before_install:
        - choco install python3 --version 3.6.8
        - export PATH="/c/Python36:/c/Python36/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel

install:
  - pip install https://download.lfd.uci.edu/pythonlibs/r5uhg2lo/Shapely-1.6.4.post1-cp36-cp36m-win_amd64.whl
  - pip install .[tests]
  - pip install flake8 flake8-docstrings

script:
  - pytest
  - flake8
